name: 📦 Deploy Astro to GitHub Pages

# Dispara al hacer push a main (cámbialo si usas otra rama)
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Obtener el código
      - uses: actions/checkout@v3

      # 2. Instalar Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Instalar dependencias y construir
      - run: npm ci
      - run: npm run build

      # Crear archivo .nojekyll para evitar procesamiento Jekyll
      - name: Create .nojekyll file
        run: touch dist/.nojekyll

      # 4. Publicar en gh-pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages        # rama de destino
          folder: dist            # carpeta que genera Astro
          clean: true             # limpiar la rama antes de subir
          single-commit: false
          commiter-message: "Deploy GitHub Pages [skip ci]"
          commit-message: "Deploy GitHub Pages [skip ci]"
          git-config-name: "GitHub Actions"
          git-config-email: "github-actions[bot]@users.noreply.github.com"
          nojekyll: true      # <-- evita que Jekyll ignore _astro
